name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          registry-url: "https://npm.pkg.github.com/"
          scope: "@MarkusBansky"

      - name: Install dependencies
        run: bun install

      - name: Build package
        run: bun run build || true

      - name: Publish to GitHub Packages
        run: bunx npm publish --access=restricted
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
